### ISSUE TITLE
Testing more stuff

### ISSUE THREAD

**Issue by apex-inc** [tj/go-news#3]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sapien sem, euismod quis diam ut, auctor commodo libero. Donec ultrices erat nisi, ac consectetur ipsum euismod eget. Donec varius sodales justo et suscipit. Curabitur non metus in nulla vehicula pulvinar. Mauris eget turpis placerat, gravida ipsum sit amet, viverra massa. Praesent ligula arcu, egestas at semper non, laoreet sed metus. Suspendisse potenti. Quisque scelerisque volutpat nisi, id lacinia eros euismod faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer ut dolor non mauris auctor finibus in in sem. Pellentesque cursus est at eros dapibus condimentum. Aliquam interdum massa viverra ultricies posuere. Nunc dapibus laoreet justo, finibus aliquam justo placerat eget.

Curabitur vulputate, dolor a vulputate congue, lectus est elementum nulla, a congue sem metus vitae risus. Curabitur congue sem eu risus molestie accumsan. Donec egestas malesuada semper. Vivamus sem leo, commodo sit amet dignissim sit amet, dignissim a diam. Donec odio dolor, pharetra vitae ullamcorper eu, fermentum eget ligula. Nunc rhoncus augue odio, et pretium lorem tincidunt eget. Nam a dui cursus.

```go
// Parse returns the rgb parsed from a color hex string.
func Parse(s string) (r, g, b uint8) {
	m := re.FindStringSubmatch(s)
	rv, _ := strconv.ParseInt(m[1], 16, 0)
	gv, _ := strconv.ParseInt(m[2], 16, 0)
	bv, _ := strconv.ParseInt(m[3], 16, 0)
	r = uint8(rv)
	g = uint8(gv)
	b = uint8(bv)
	return
}
```

Vestibulum libero id, ultricies mi. Ut non vestibulum tellus, vel sagittis magna. Donec molestie lacinia orci vitae ullamcorper. Proin vitae tortor tristique, iaculis purus et, semper arcu. Fusce eleifend, metus vel rutrum gravida, dolor arcu faucibus sapien, ac lobortis libero urna at lectus. Vivamus quam arcu, pellentesque ut nulla non, dictum feugiat est. Aliquam neque ipsum, hendrerit eget diam ut, hendrerit tempus velit. Aliquam cursus interdum massa vel efficitur.

```
strconv.ParseInt(m[3], 16, 0)
```

**Comment by tj** [comment]
Looks good to me,
just testing some random stuff... dont mind me :D
